# Generated by Django 3.2.9 on 2021-11-20 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detalleventas',
            fields=[
                ('codigo_venta', models.IntegerField(primary_key=True, serialize=False)),
                ('codigo_producto', models.IntegerField()),
                ('cedula_cliente', models.IntegerField()),
                ('consecutivo', models.IntegerField()),
                ('iva_compra', models.FloatField()),
                ('precio_compra', models.FloatField()),
                ('precio_venta', models.FloatField()),
            ],
        ),
    ]
